### PR TITLE
Fix support for bracketed Unicode escapes in template literals

### LINKED ISSUE #349: Bug: bracketed Unicode escapes not supported
[Issuehunt badges](https://issuehunt.io/r/chalk/chalk/issues/349)

Repro:

```js
// example.js
const chalk = require('chalk')

console.log(chalk`\u{2192} Running test {bold foo}...`)
```

Expected output:
<pre><code>&#x2192; Running test <strong>foo</strong>...</code></pre>

Actual output:
```
Error: Found extraneous } in Chalk template literal
    at node_modules/chalk/templates.js:109:11
    at String.replace (<anonymous>)
    at module.exports (node_modules/chalk/templates.js:99:6)
    at chalkTag (node_modules/chalk/index.js:221:9)
    at Chalk.chalk.template (node_modules/chalk/index.js:36:20)
    at Object.<anonymous> (example.js:3:17)
```

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $50.00)

- [issuehunt issuehunt](https://issuehunt.io/u/issuehunt) ($50.00)
### Submitted pull Requests
- [#350 Fix bracketed unicode escapes in template literals](https://issuehunt.io/r/chalk/chalk/pull/350)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/chalk/chalk/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### PR DESCRIPTION
**Pull request by Qix-**
Fixes #349.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Referenced issues

This pull request has been submitted to:
- [#349: Bug: bracketed Unicode escapes not supported](https://issuehunt.io/repos/11855195/issues/349)
---

IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### CODE REVIEW

File: templates.js [hunk 1]
```diff
@@ -1,8 +1,8 @@
 'use strict';
-const TEMPLATE_REGEX = /(?:\\(u[a-f\d]{4}|x[a-f\d]{2}|.))|(?:\{(~)?(\w+(?:\([^)]*\))?(?:\.\w+(?:\([^)]*\))?)*)(?:[ \t]|(?=\r?\n)))|(\})|((?:.|[\r\n\f])+?)/gi;
+const TEMPLATE_REGEX = /(?:\\(u(?:[a-f\d]{4}|\{[a-f\d]{1,5}\})|x[a-f\d]{2}|.))|(?:\{(~)?(\w+(?:\([^)]*\))?(?:\.\w+(?:\([^)]*\))?)*)(?:[ \t]|(?=\r?\n)))|(\})|((?:.|[\r\n\f])+?)/gi;
```
Comment (j-f1) [inline templates.js]: The Unicode standard [allows](https://www.unicode.org/charts/PDF/U10FF80.pdf) six-character code points. Would it make sense to allow this?

Additionally, in the spec, [unicode escape sequences](https://read262.netlify.com/ecmascript-language-lexical-grammar/ecmascript-language-lexical-grammar-literals#prod-UnicodeEscapeSequence) with braces like this allow [a hex value ≤ 0x10FFFF](https://read262.netlify.com/ecmascript-language-lexical-grammar/ecmascript-language-lexical-grammar-literals#prod-CodePoint).

Comment (Qix-) [reply templates.js]: Yep, good catch. I was testing with a bad value.
